# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest Test CI

on:
  push:
    branches: [ "master", "release/*", "test" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: echo "${{ github.event.head_commit.modified }}"
    - uses: actions/checkout@v3
    - run: echo "${{ github.event.head_commit.modified }}"
    - name: Use Node.js ${{ matrix.node-version }}
      if: contains(github.event.head_commit.modified, '**.{js,vue,md}')
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - if: contains(github.event.head_commit.modified, '**.{js,vue,md}')
      run: npm ci
    - if: contains(github.event.head_commit.modified, '**.{js,vue,md}')
      run: npm test
